# Generated by Django 4.2.20 on 2025-04-01 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Tour_Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_title', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('place_image', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(help_text='Duration in days')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('top_package', models.BooleanField(default=False)),
                ('budget_friendly', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('auto_expire', models.BooleanField(default=True)),
                ('booking_count', models.IntegerField(default=0)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tour package',
                'verbose_name_plural': 'Tour packages',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('second_name', models.CharField(max_length=150)),
                ('phone_no', models.CharField(max_length=15)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.TextField()),
                ('company', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Registered Vendor',
                'verbose_name_plural': 'Registered Vendors',
            },
        ),
        migrations.CreateModel(
            name='Manage_Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Adventures.create_tour_package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='create_tour_package',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adventures.vendor'),
        ),
    ]
